language: php

php:
  - 7.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
  - composer require --dev php-coveralls/php-coveralls --no-interaction

script:
  - vendor/bin/phpunit

after_script:
  - php vendor/bin/php-coveralls
